### ISSUE TITLE
[INFO] Waiting for good HMR Solution before updating T2S to Meteor 1.3

### ISSUE THREAD

**Issue by D1no** [D1no/touch2s#12]
Meteor 1.3 finally landed and it is great! Modules, ecmascript, and many other goodies arrived. So the question is, why is Touch2S not getting updated? The reason is, that Touch2S uses Webpack to both achieve
- server side rendering
- provide a fast, hot module replacement (HMR) driven developer experience without reloads

At this point, I would love to kick out webpack to simplify this stack and may invest further time to make Touch2S an easy go to Framework7 implementation. Sadly, kicking out webpack is not so easy. We would lose easy Server-Side-Rendering and face reload times (again) between any changes in our code.

For now, I am primarily watching [a babel plugin based approach that enables Hotloading in native Meteor](https://forums.meteor.com/t/react-hotloading-in-native-meteor-is-ready-i-e-no-webpack/17523), the currently used [meteor react router ssr package](https://github.com/thereactivestack/meteor-react-router-ssr), the [webpack package for meteor](https://forums.meteor.com/t/use-webpack-with-meteor-simply-by-adding-packages-meteor-webpack-1-0-is-out/18819) and of course the overall development of meteor and its issue on build times.

If you have suggestions, please make them. I am also open to pull requests and other ideas.

Dino

**Comment by tscans** [comment]
@D1no I just stumbled upon this and I'm stoked to try it on 1.3. How has your progress been?

**Comment by bearcanrun** [comment]
I was inspired by this project, but really wanted to move to 1.3. So I explored and came upon [Onsen UI](https://onsen.io/v2/), which has it's own react components library on npm. With meteor 1.3, you just import like any other npm library. I'm still using webpack, but you could easily use it without webpack. It doesn't address the above issue though, just a thought.

**Comment by tommy16p** [comment]
I'm going to look into this. Thank you for bringing it to my attention.
