### ISSUE TITLE
How about react-mixin?

### ISSUE THREAD

**Issue by ghost** [D1no/touch2s#3]
Sorry, newbie question -

Why don't you use https://www.npmjs.com/package/react-mixin over ultimatejs:tracker-react ? Thoughts?

Thanks

**Comment by D1no** [comment]
TrackerReact is going to be replaced with the emergence of ultimatejs' tracker react component and Meteor 1.3.

The reason for the current style is that the original Meteor Mixin is currently handled this way - for an easy replacement.

In the future, mixins should be handled as ES6 extend.
