### ISSUE TITLE
Sample code error: A semicolon is required after a class property

### ISSUE THREAD

**Issue by txs** [D1no/touch2s#7]
Once I use the sample code. First it cannot find the packages.json
ERROR: packages.json parsing error [ ENOENT, no such file or directory '~~/packages.json' ]
And then the semicolon doesn't work either
A semicolon is required after a class property
like the below link photo
http://i.imgur.com/hAP20Dx.png

**Comment by D1no** [comment]
There is a recent incompatibility with newer node versions (Meteor uses the LTS node v0.10.40). I assume you have a newer node/npm version installed (v4 or v5).

Meteor-Webpack needs to install npm to get npm packages (this will soon be changed with Meteor 1.3 coming in a few weeks with native NPM support), which relies on your local node version.

Do the following:
- change your node version to `v0.10.40` (I use `n` which is a very convenient node version manager for fast switching https://github.com/tj/n)
- re-download/clone the repo in a new folder
  - or delete the `/node_modules` symlink folder
  - and delete the `/.meteor/local` folder
- run `meteor`

Note that the very first build can take quite a while, sometimes even looking like the process is frozen.

Currently, the process is sub-optimal but with the release of Meteor 1.3 with native Npm support and an update to the used node version, this boilerplate will be streamlined.

Please let me know if this helped.

**Comment by D1no** [comment]
I updated the readme

**Comment by txs** [comment]
Thanks for the help! It's working now!
