### ISSUE TITLE
lazy load components

### ISSUE THREAD

**Issue by txs** [D1no/touch2s#8]
How do I lazy load components?

Since ReactRouterSSR doesn't have the "routes" props. How do I call the module export from the other jsx file. Please help! Thanks!

https://medium.com/@SamCorcos/meteor-webpack-react-router-a-basic-template-with-code-splitting-ac2f95d151e2#.4rwhilget

module.exports = {
  getComponent(location, cb) {
    require.ensure([], (require) => {
      cb(null, require('./components/Home'))
    })
  }
}

**Comment by txs** [comment]
I use flow router to build it!

**Comment by txs** [comment]
using require ensure doesn't create a new bundle. How do I create a new bundle

**Comment by D1no** [comment]
Webpack is responsible for that. Please ask there.
